name: sliip
version: "0.0.0.0"

dependencies:
  - base
  - megaparsec
  - containers

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -fwarn-tabs
    - -O0

executables:
  sliip:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - sliip
      - optparse-applicative

tests:
  tests:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - sliip
      - hspec
      - hspec-discover
      - silently
