name:    sliip
version: "0.0.0.0"

dependencies:
  - base

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -fwarn-tabs
    - -O0

executables:
  sliip:
    main: main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sliip
