cabal-version: 3.0
name: sliip
version: 0.0.0.0
license: MIT
license-file: LICENSE
author: haruki7049
maintainer: tontonkirikiri@gmail.com
build-type: Simple

common warnings
  ghc-options: -Wall

library
  import: warnings
  exposed-modules:
    Sliip
    Sliip.Evaluator
    Sliip.Evaluator.Utils
    Sliip.Parser

  build-depends:
    base,
    containers,
    megaparsec,

  hs-source-dirs: src
  default-language: Haskell2010

executable sliip
  import: warnings
  main-is: Main.hs
  build-depends:
    base,
    containers,
    megaparsec,
    optparse-applicative,
    sliip,

  hs-source-dirs: app
  default-language: Haskell2010

test-suite tests
  import: warnings
  type: exitcode-stdio-1.0
  main-is: Spec.hs
  other-modules:
    Paths_sliip
    SliipEvaluatorSpec
    SliipEvaluatorUtilsSpec
    SliipParserSpec

  build-depends:
    base,
    containers,
    hspec,
    hspec-discover,
    megaparsec,
    silently,
    sliip,

  hs-source-dirs: test
  default-language: Haskell2010
